sudo: required
services:
  - docker
before_install:
  - docker build -t weylandxlcrb/docker-react -f Dockerfile.dev .
script:
  - docker run weylandxlcrb/docker-react ./node_modules/.bin/cross-env CI=true npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-800776018205"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY