sudo: required
services:
  - docker
before_install:
  - docker build -t weylandxlcrb/docker-react -f Dockerfile.dev .
script:
  - docker run weylandxlcrb/docker-react npm run test -- --coverage CI=true